### ISSUE TITLE
Add New Language: PostScript

### ISSUE THREAD

**Issue by zzo38** [ericspring08/Awesome-Programming-Languages#26]
# Description
PostScript is a stack-based programming language, mainly used for vector graphics and printing; however, it is also a general-purpose programming language which can be used for other uses too.

**Comment by MrKrishnaAgarwal** [comment]
https://github.com/MrKrishnaAgarwal/Awesome-Programming-Languages

**Comment by devarshishimpi** [comment]
I'll take on this issue
