### ISSUE TITLE
Add New Language: Crystal

### ISSUE THREAD

**Issue by drakmail** [ericspring08/Awesome-Programming-Languages#30]
# Description

Crystal is a programming language with the following goals:

* Have a syntax similar to Ruby (but compatibility with it is not a goal)
* Statically type-checked but without having to specify the type of variables or method arguments.
* Be able to call C code by writing bindings to it in Crystal.
* Have compile-time evaluation and generation of code, to avoid boilerplate code.
* Compile to efficient native code.

**Comment by devarshishimpi** [comment]
I'll work on this
