### ISSUE TITLE
Add New Language: V

### ISSUE THREAD

**Issue by drakmail** [ericspring08/Awesome-Programming-Languages#32]
# Description

Simple language for building maintainable programs. You can learn the entire language by going through the [documentation](https://github.com/vlang/v/blob/master/doc/docs.md) over a weekend, and in most cases there's only one way to do something. This results in simple, readable, and maintainable code. Despite being simple, V gives a lot of power to the developer and can be used in pretty much every field, including systems programming, webdev, gamedev, GUI, mobile, science, embedded, tooling, etc. V is very similar to Go. If you know Go, you already know ≈80% of V.

**Comment by MrKrishnaAgarwal** [comment]
https://github.com/MrKrishnaAgarwal/Awesome-Programming-Languages

**Comment by Arpit-mohankar** [comment]
hey @drakmail can i work on this

**Comment by MrKrishnaAgarwal** [comment]
> hey @drakmail can i work on this

Visit my profile and contact me, we can work together.

I'll be very happy 😁

**Comment by ericspring08** [comment]
> hey @drakmail can i work on this

Sure, feel free to work on any issue. Any support world be gladly appreciated!

**Comment by ericspring08** [comment]
Solved with #33
