### ISSUE TITLE
Add New Language: CSS

### ISSUE THREAD

**Issue by devarshishimpi** [ericspring08/Awesome-Programming-Languages#34]
# Description
CSS also know as Cascading Style Sheets used for designing web pages.

**Comment by devarshishimpi** [comment]
Also, can you assign this to me?

**Comment by ericspring08** [comment]
Sure

**Comment by devarshishimpi** [comment]
Thanks, I will open the PR asap with the docs for the same

**Comment by devarshishimpi** [comment]
https://github.com/ericspring08/Awesome-Programming-Languages/pull/37

**Comment by ericspring08** [comment]
Fixed with #37
