### ISSUE TITLE
Add New Language: HTML

### ISSUE THREAD

**Issue by devarshishimpi** [ericspring08/Awesome-Programming-Languages#35]
# Description
The HyperText Markup Language or HTML is the standard markup language for documents designed to be displayed in a web browser.

**Comment by devarshishimpi** [comment]
Also can you assign this to me?

**Comment by ericspring08** [comment]
Sure

**Comment by devarshishimpi** [comment]
Thanks, I will open the PR asap with the docs for the same.

**Comment by devarshishimpi** [comment]
https://github.com/ericspring08/Awesome-Programming-Languages/pull/36

**Comment by ericspring08** [comment]
Fixed with #36
