### ISSUE TITLE
Add New Language: Git

### ISSUE THREAD

**Issue by devarshishimpi** [ericspring08/Awesome-Programming-Languages#41]
# Description
Provide a description of the programming language.

**Comment by devarshishimpi** [comment]
Hi, Can you please assign this to me?

**Comment by devarshishimpi** [comment]
https://github.com/ericspring08/Awesome-Programming-Languages/pull/48

**Comment by ericspring08** [comment]
fixed with #48

**Comment by zzo38** [comment]
Git is not a programming language.

**Comment by devarshishimpi** [comment]
@ericspring08 Could we change the topic to something like tools or something?

**Comment by devarshishimpi** [comment]
Even HTML isn't a programming language.
