### ISSUE TITLE
Add New Tool: React JS

### ISSUE THREAD

**Issue by MrKrishnaAgarwal** [ericspring08/Awesome-Programming-Languages#61]
# Description

[React is a free and open-source front-end JavaScript library for building user interfaces based on UI components. It is maintained by Meta and a community of individual developers and companies.](https://www.bing.com/ck/a?!&&p=1422713c4b132384JmltdHM9MTY2NDkyODAwMCZpZ3VpZD0xZjc0MDQzNS00OGZlLTYwZDgtMDlmNS0xNjEwNDk0YzYxMTQmaW5zaWQ9NTU1MQ&ptn=3&hsh=3&fclid=1f740435-48fe-60d8-09f5-1610494c6114&psq=react+js&u=a1aHR0cHM6Ly9lbi53aWtpcGVkaWEub3JnL3dpa2kvUmVhY3RfKEphdmFTY3JpcHRfbGlicmFyeSk&ntb=1)

cc @devarshishimpi

**Comment by MrKrishnaAgarwal** [comment]
**Please assign to me**

**Comment by devarshishimpi** [comment]
React JS is not a Programming language

**Comment by devarshishimpi** [comment]
But, if you do want to add it, you can add it to the "Tools and Related" Section

**Comment by devarshishimpi** [comment]
I'll take this issue

**Comment by MrKrishnaAgarwal** [comment]
> I'll take this issue

But I was about to make a pr, I forgot about it.
Its already ready.
Making a pr right now

**Comment by devarshishimpi** [comment]
> > I'll take this issue
> 
> But I was about to make a pr, I forgot about it. Its already ready. Making a pr right now

Okay no worries

**Comment by MrKrishnaAgarwal** [comment]
> > > I'll take this issue
> > 
> > But I was about to make a pr, I forgot about it. Its already ready. Making a pr right now
> 
> Okay no worries

Thanks =)
