### ISSUE TITLE
I want to add a button that takes you to the top of the page in main webpage.

### ISSUE THREAD

**Issue by abhay-raj19** [ericspring08/Awesome-Programming-Languages#68]
I want to add a move to top button in the bottom right corner so that while surfing the page if the user wants to move to the top
at of the page , by directly clicking on that button the user can move to the top of the page .

Button specification
→ Round Top arrow button
→ Hovering effect

Describe how the idea would be helpful
while surfing in the bottom sections of the webpage if the user directly wants to move at the top then it will be easily possible
and handy for the user to click on that button and reach at the top.

Some what like this
![image](https://user-images.githubusercontent.com/96302417/198319369-da099271-841e-4eeb-bd6f-fc237379018e.png)

PLs do label it with Hacktoberfest and hacktoberfest : Accepted labels.

**Comment by devarshishimpi** [comment]
Sure

**Comment by abhay-raj19** [comment]
I am not getting the main HTML and CSS file for this page in your repo. 

https://ericspring08.github.io/Awesome-Programming-Languages/

Pls let me know so that i can make changes suggested under #68

<img width="195" alt="image" src="https://user-images.githubusercontent.com/96302417/198474856-44ec43b8-ff3a-4a07-acfd-48b1cff4d122.png">

**Comment by devarshishimpi** [comment]
@abhay-raj19 The website uses Github-Pages for hosting using markdown and not HTML and CSS

**Comment by abhay-raj19** [comment]
ohkk.. got it got it.
